version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  mongodb:
    networks:
      - backend
    image: mongo:latest
    container_name: mutant
    ports:
      - 27017:27017
  mutant-app-image:
    networks:
      - backend
    image: mutant-app-image
    container_name: mutant-app-image
    ports:
      - 8080:8080
    links:
      - mongodb