version: '2'
services:
  mongodb:
    container_name: mutant-datastore
    image: mongo:3.2
    command: mongod --smallfiles
  web:
    container_name: mutant-service
    build: build/libs
    image: mutant-service-image
    depends_on: # mutant-datastore will be started before the mutant-service
      - mongodb
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/mutant