spring:
  data:
    mongodb:
      host: '${MONGO_HOST:localhost}'
      port: 27017
      database: '${MONGO_DB:mutant}'

  cloud:
    kubernetes:
      discovery:
        register: true

      config:
        enabled: true
        sources:
          - namespace: default
            name: mutant-db-config
      reload:
        enabled: true
        mode: polling
        period: 1000